name: flutter_document_recognition
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.0
  camera: ^0.10.5+9
  path: ^1.9.0
  path_provider: ^2.1.3
  google_mlkit_commons: ^0.7.1
  google_mlkit_object_detection: ^0.13.0
  image: ^4.1.7
  identity_document_detection:
    path: packages/IdentityDocumentDetection

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/ml/
    - assets/images/